Update README.md
Because I try to test on Python 2.6 and show error

```AttributeError: 'module' object has no attribute 'captureWarnings'```

and logging.captureWarnings only in Python 2.7